# Catalog of Watson's db2 queries

# Ask Db2 for list of tables/views 
GET_OBJECTS_SEARCH = """
SELECT 
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME as OBJECT_NAME,
    TABLE_TYPE as OBJECT_TYPE,
    REMARKS as DESCRIPTION
FROM QSYS2.SYSTABLES
WHERE (TABLE_SCHEMA = ? OR ? IS NULL)
  AND (TABLE_NAME LIKE ? OR ? IS NULL)
  AND (TABLE_TYPE = ? OR ? IS NULL)
FETCH FIRST 100 ROWS ONLY
"""
