# Catalog of Watson's db2 queries

# Ask Db2 for list of tables/views 
GET_OBJECTS_SEARCH = """
SELECT 
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME as OBJECT_NAME,
    TABLE_TYPE as OBJECT_TYPE,
    REMARKS as DESCRIPTION
FROM QSYS2.SYSTABLES
WHERE (TABLE_SCHEMA = ? OR ? IS NULL)
  AND (TABLE_NAME LIKE ? OR ? IS NULL)
  AND (TABLE_TYPE = ? OR ? IS NULL)
FETCH FIRST 100 ROWS ONLY
"""

# Fetch column details for a specific table
GET_COLUMNS_FOR_TABLE = """
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    LENGTH,
    COLUMN_TEXT,
    IS_IDENTITY
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
ORDER BY COLUMN_NAME
"""
